
# College Database
COLLEGE_DB = [
    # 1-5
    {"college_id": 1, "college_name": "Govt. Gandhi Memorial Science College, Srinagar", "stream": "Science", "subjects": ["Physics","Chemistry","Biology","Mathematics","Computer Science"], "distance_km":5, "travel_time_min":15, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Srinagar", "tuition_fees":22000, "rating":4.5, "faculty_count":45, "placement_opportunities":"High", "average_package":6.5, "facilities":["Labs","Library","WiFi","Sports"], "extra_curricular":["Music Club","Science Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC A", "entry_criteria":"Merit-based"},
    {"college_id": 2, "college_name": "Govt. Degree College, Anantnag", "stream": "Arts", "subjects": ["Literature","History","Political Science","Sociology","Fine Arts"], "distance_km":8, "travel_time_min":25, "hostel":True, "accommodation_type":"Shared", "scholarship":False, "scholarship_eligibility":"N/A", "city":"Anantnag", "tuition_fees":15000, "rating":4.2, "faculty_count":35, "placement_opportunities":"Medium", "average_package":3.5, "facilities":["Library","Auditorium","WiFi"], "extra_curricular":["Drama Club","Literature Society"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 3, "college_name": "Govt. MAM College, Jammu", "stream": "Commerce", "subjects": ["Accounting","Economics","Finance","Business Studies","Marketing"], "distance_km":10, "travel_time_min":30, "hostel":False, "accommodation_type":"PG/Private", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Jammu", "tuition_fees":22000, "rating":4.3, "faculty_count":40, "placement_opportunities":"High", "average_package":5.5, "facilities":["Library","WiFi","Computer Lab"], "extra_curricular":["Debate Club","Entrepreneurship Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC A", "entry_criteria":"Merit-based"},
    {"college_id": 4, "college_name": "Govt. Degree College, Baramulla", "stream": "Science", "subjects": ["Physics","Chemistry","Mathematics","Computer Science"], "distance_km":12, "travel_time_min":40, "hostel":True, "accommodation_type":"Single", "scholarship":True, "scholarship_eligibility":"Merit & SC/ST", "city":"Baramulla", "tuition_fees":20000, "rating":4.1, "faculty_count":38, "placement_opportunities":"Medium", "average_package":4.5, "facilities":["Labs","Library","Sports"], "extra_curricular":["Science Club","Sports Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 5, "college_name": "Govt. Degree College, Sopore", "stream": "Arts", "subjects": ["Psychology","Philosophy","History","Literature"], "distance_km":15, "travel_time_min":50, "hostel":False, "accommodation_type":"PG/Private", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Sopore", "tuition_fees":16000, "rating":4.0, "faculty_count":30, "placement_opportunities":"Low", "average_package":3.0, "facilities":["Library","WiFi"], "extra_curricular":["Drama Club","Music Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},

    # 6-10
    {"college_id": 6, "college_name": "Govt. Polytechnic College, Srinagar", "stream": "Vocational", "subjects": ["Electrician","Hospitality","Fashion Design","Technical Diploma","Skilled Trades"], "distance_km":7, "travel_time_min":20, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Srinagar", "tuition_fees":18000, "rating":4.2, "faculty_count":28, "placement_opportunities":"Medium", "average_package":4.0, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Technical Club","Sports Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 7, "college_name": "Govt. Degree College, Udhampur", "stream": "Commerce", "subjects": ["Economics","Finance","Business Administration"], "distance_km":20, "travel_time_min":60, "hostel":False, "accommodation_type":"PG/Private", "scholarship":False, "scholarship_eligibility":"N/A", "city":"Udhampur", "tuition_fees":23000, "rating":4.1, "faculty_count":32, "placement_opportunities":"Medium", "average_package":4.8, "facilities":["Library","WiFi"], "extra_curricular":["Entrepreneurship Club","Debate Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 8, "college_name": "Govt. Degree College for Women, Srinagar", "stream": "Arts", "subjects": ["Fine Arts","Music","Drama","Sociology"], "distance_km":6, "travel_time_min":20, "hostel":True, "accommodation_type":"Single", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Srinagar", "tuition_fees":15000, "rating":4.3, "faculty_count":28, "placement_opportunities":"Medium", "average_package":3.8, "facilities":["Library","Auditorium","WiFi"], "extra_curricular":["Music Club","Drama Club"], "transport_available":True, "gender_specific":"Girls", "accreditation":"NAAC A", "entry_criteria":"Merit-based"},
    {"college_id": 9, "college_name": "Govt. Science College, Jammu", "stream": "Science", "subjects": ["Computer Science","Mathematics","Electronics"], "distance_km":9, "travel_time_min":25, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Jammu", "tuition_fees":25000, "rating":4.7, "faculty_count":40, "placement_opportunities":"High", "average_package":7.0, "facilities":["Labs","Library","WiFi","Sports"], "extra_curricular":["Coding Club","Science Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC A", "entry_criteria":"Merit-based"},
    {"college_id": 10, "college_name": "Govt. Degree College, Pulwama", "stream": "Vocational", "subjects": ["Automobile","IT","Textile Designing"], "distance_km":18, "travel_time_min":55, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Pulwama", "tuition_fees":19000, "rating":4.2, "faculty_count":30, "placement_opportunities":"Medium", "average_package":4.0, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Technical Club","Art Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},

    # 11-20
    {"college_id": 11, "college_name": "Govt. Degree College, Rajouri", "stream": "Arts", "subjects": ["History","Political Science","Literature"], "distance_km":25, "travel_time_min":75, "hostel":False, "accommodation_type":"PG/Private", "scholarship":False, "scholarship_eligibility":"N/A", "city":"Rajouri", "tuition_fees":16000, "rating":4.0, "faculty_count":28, "placement_opportunities":"Low", "average_package":3.0, "facilities":["Library","WiFi"], "extra_curricular":["Debate Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 12, "college_name": "Govt. Degree College, Kathua", "stream": "Science", "subjects": ["Physics","Chemistry","Mathematics"], "distance_km":18, "travel_time_min":50, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Kathua", "tuition_fees":21000, "rating":4.3, "faculty_count":35, "placement_opportunities":"Medium", "average_package":4.5, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Science Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 13, "college_name": "Govt. Degree College, Kulgam", "stream": "Commerce", "subjects": ["Accounting","Finance","Business Studies"], "distance_km":20, "travel_time_min":60, "hostel":False, "accommodation_type":"PG/Private", "scholarship":True, "scholarship_eligibility":"Merit & SC/ST", "city":"Kulgam", "tuition_fees":22000, "rating":4.2, "faculty_count":30, "placement_opportunities":"Medium", "average_package":4.8, "facilities":["Library","WiFi"], "extra_curricular":["Debate Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 14, "college_name": "Govt. Degree College, Anantnag", "stream": "Vocational", "subjects": ["Hospitality","ITI Electrician","Technical Diploma"], "distance_km":10, "travel_time_min":30, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Anantnag", "tuition_fees":18000, "rating":4.1, "faculty_count":28, "placement_opportunities":"Medium", "average_package":4.2, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Technical Club","Music Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 15, "college_name": "Govt. Degree College, Shopian", "stream": "Arts", "subjects": ["Psychology","Sociology","Literature"], "distance_km":12, "travel_time_min":40, "hostel":False, "accommodation_type":"PG/Private", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Shopian", "tuition_fees":15000, "rating":4.0, "faculty_count":25, "placement_opportunities":"Low", "average_package":3.2, "facilities":["Library","WiFi"], "extra_curricular":["Drama Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 16, "college_name": "Govt. Degree College, Leh", "stream": "Science", "subjects": ["Physics","Chemistry","Mathematics","Computer Science"], "distance_km":5, "travel_time_min":15, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Leh", "tuition_fees":23000, "rating":4.5, "faculty_count":32, "placement_opportunities":"Medium", "average_package":5.0, "facilities":["Labs","Library","WiFi","Sports"], "extra_curricular":["Science Club","Sports Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC A", "entry_criteria":"Merit-based"},
    {"college_id": 17, "college_name": "Govt. Degree College, Kargil", "stream": "Commerce", "subjects": ["Accounting","Economics","Finance"], "distance_km":8, "travel_time_min":25, "hostel":True, "accommodation_type":"Single", "scholarship":True, "scholarship_eligibility":"Merit & SC/ST", "city":"Kargil", "tuition_fees":22000, "rating":4.3, "faculty_count":28, "placement_opportunities":"Medium", "average_package":4.5, "facilities":["Library","WiFi"], "extra_curricular":["Debate Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 18, "college_name": "Govt. Degree College, Budgam", "stream": "Arts", "subjects": ["History","Literature","Political Science"], "distance_km":10, "travel_time_min":35, "hostel":False, "accommodation_type":"PG/Private", "scholarship":False, "scholarship_eligibility":"N/A", "city":"Budgam", "tuition_fees":15000, "rating":4.0, "faculty_count":28, "placement_opportunities":"Low", "average_package":3.0, "facilities":["Library","WiFi"], "extra_curricular":["Music Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 19, "college_name": "Govt. Degree College, Bandipora", "stream": "Vocational", "subjects": ["Textile Designing","ITI Electrician","Hospitality"], "distance_km":15, "travel_time_min":50, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Bandipora", "tuition_fees":18000, "rating":4.1, "faculty_count":30, "placement_opportunities":"Medium", "average_package":4.0, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Technical Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 20, "college_name": "Govt. Degree College, Doda", "stream": "Science", "subjects": ["Physics","Chemistry","Biology","Mathematics"], "distance_km":18, "travel_time_min":60, "hostel":True, "accommodation_type":"Single", "scholarship":True, "scholarship_eligibility":"Merit & SC/ST", "city":"Doda", "tuition_fees":22000, "rating":4.2, "faculty_count":35, "placement_opportunities":"Medium", "average_package":4.5, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Science Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},

    # 21-30
    {"college_id": 21, "college_name": "Govt. Degree College, Ganderbal", "stream": "Science", "subjects": ["Physics","Chemistry","Biology","Mathematics"], "distance_km":7, "travel_time_min":20, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Ganderbal", "tuition_fees":21000, "rating":4.3, "faculty_count":32, "placement_opportunities":"Medium", "average_package":4.5, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Science Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 22, "college_name": "Govt. Degree College, Kupwara", "stream": "Arts", "subjects": ["History","Literature","Political Science"], "distance_km":12, "travel_time_min":40, "hostel":False, "accommodation_type":"PG/Private", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Kupwara", "tuition_fees":15000, "rating":4.0, "faculty_count":28, "placement_opportunities":"Low", "average_package":3.0, "facilities":["Library","WiFi"], "extra_curricular":["Drama Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 23, "college_name": "Govt. Degree College, Reasi", "stream": "Commerce", "subjects": ["Accounting","Finance","Business Studies"], "distance_km":18, "travel_time_min":55, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit & SC/ST", "city":"Reasi", "tuition_fees":22000, "rating":4.2, "faculty_count":30, "placement_opportunities":"Medium", "average_package":4.8, "facilities":["Library","WiFi"], "extra_curricular":["Debate Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 24, "college_name": "Govt. Degree College, Poonch", "stream": "Arts", "subjects": ["Psychology","Sociology","Literature"], "distance_km":22, "travel_time_min":70, "hostel":False, "accommodation_type":"PG/Private", "scholarship":False, "scholarship_eligibility":"N/A", "city":"Poonch", "tuition_fees":15000, "rating":4.0, "faculty_count":25, "placement_opportunities":"Low", "average_package":3.2, "facilities":["Library","WiFi"], "extra_curricular":["Music Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 25, "college_name": "Govt. Degree College, Ramban", "stream": "Science", "subjects": ["Physics","Chemistry","Mathematics","Computer Science"], "distance_km":16, "travel_time_min":50, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Ramban", "tuition_fees":22000, "rating":4.2, "faculty_count":32, "placement_opportunities":"Medium", "average_package":4.5, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Science Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 26, "college_name": "Govt. Degree College, Kishtwar", "stream": "Vocational", "subjects": ["ITI Electrician","Automobile","Hospitality"], "distance_km":20, "travel_time_min":60, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Kishtwar", "tuition_fees":18000, "rating":4.1, "faculty_count":28, "placement_opportunities":"Medium", "average_package":4.0, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Technical Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 27, "college_name": "Govt. Degree College, Kathua Science", "stream": "Science", "subjects": ["Physics","Chemistry","Mathematics","Biology"], "distance_km":15, "travel_time_min":45, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit & SC/ST", "city":"Kathua", "tuition_fees":21000, "rating":4.3, "faculty_count":32, "placement_opportunities":"Medium", "average_package":4.5, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Science Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 28, "college_name": "Govt. Degree College, Udhampur Arts", "stream": "Arts", "subjects": ["History","Literature","Political Science"], "distance_km":10, "travel_time_min":35, "hostel":False, "accommodation_type":"PG/Private", "scholarship":False, "scholarship_eligibility":"N/A", "city":"Udhampur", "tuition_fees":15000, "rating":4.0, "faculty_count":28, "placement_opportunities":"Low", "average_package":3.0, "facilities":["Library","WiFi"], "extra_curricular":["Drama Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 29, "college_name": "Govt. Degree College, Leh Vocational", "stream": "Vocational", "subjects": ["Technical Diploma","Hospitality","IT"], "distance_km":5, "travel_time_min":15, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Leh", "tuition_fees":19000, "rating":4.2, "faculty_count":30, "placement_opportunities":"Medium", "average_package":4.0, "facilities":["Labs","Library","WiFi"], "extra_curricular":["Technical Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 30, "college_name": "Govt. Degree College, Kargil Arts", "stream": "Arts", "subjects": ["Psychology","Sociology","Literature"], "distance_km":8, "travel_time_min":25, "hostel":False, "accommodation_type":"PG/Private", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Kargil", "tuition_fees":15000, "rating":4.0, "faculty_count":25, "placement_opportunities":"Low", "average_package":3.0, "facilities":["Library","WiFi"], "extra_curricular":["Music Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},

    # 31-50
    {"college_id": 31, "college_name": "Govt. Degree College, Srinagar Arts 2", "stream": "Arts", "subjects":["Literature","History","Sociology"], "distance_km":5, "travel_time_min":15, "hostel":True,"accommodation_type":"Single", "scholarship":True,"scholarship_eligibility":"Merit-based", "city":"Srinagar", "tuition_fees":15000,"rating":4.1,"faculty_count":30,"placement_opportunities":"Medium","average_package":3.5,"facilities":["Library","WiFi"],"extra_curricular":["Drama Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 32, "college_name": "Govt. Degree College, Baramulla Arts", "stream": "Arts", "subjects":["History","Literature","Political Science"], "distance_km":12,"travel_time_min":40,"hostel":False,"accommodation_type":"PG/Private","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Baramulla","tuition_fees":15000,"rating":4.0,"faculty_count":28,"placement_opportunities":"Low","average_package":3.0,"facilities":["Library","WiFi"],"extra_curricular":["Music Club"],"transport_available":False,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 33, "college_name": "Govt. Degree College, Pulwama Arts", "stream": "Arts", "subjects":["Psychology","Sociology","Literature"], "distance_km":10,"travel_time_min":35,"hostel":False,"accommodation_type":"PG/Private","scholarship":False,"scholarship_eligibility":"N/A","city":"Pulwama","tuition_fees":15000,"rating":4.0,"faculty_count":25,"placement_opportunities":"Low","average_package":3.0,"facilities":["Library","WiFi"],"extra_curricular":["Drama Club"],"transport_available":False,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 34, "college_name": "Govt. Degree College, Anantnag Commerce 2", "stream": "Commerce", "subjects":["Accounting","Finance","Business Studies"], "distance_km":15,"travel_time_min":45,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Anantnag","tuition_fees":22000,"rating":4.2,"faculty_count":30,"placement_opportunities":"Medium","average_package":4.5,"facilities":["Library","WiFi"],"extra_curricular":["Debate Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 35, "college_name": "Govt. Degree College, Jammu Vocational 2", "stream": "Vocational", "subjects":["ITI Electrician","Automobile","Hospitality"], "distance_km":8,"travel_time_min":25,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Jammu","tuition_fees":19000,"rating":4.1,"faculty_count":28,"placement_opportunities":"Medium","average_package":4.0,"facilities":["Labs","Library","WiFi"],"extra_curricular":["Technical Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 36, "college_name": "Govt. Degree College, Kulgam Arts 2", "stream": "Arts", "subjects":["History","Literature","Political Science"], "distance_km":12,"travel_time_min":40,"hostel":False,"accommodation_type":"PG/Private","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Kulgam","tuition_fees":15000,"rating":4.0,"faculty_count":28,"placement_opportunities":"Low","average_package":3.0,"facilities":["Library","WiFi"],"extra_curricular":["Music Club"],"transport_available":False,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 37, "college_name": "Govt. Degree College, Budgam Science 2", "stream": "Science", "subjects":["Physics","Chemistry","Mathematics","Biology"], "distance_km":8,"travel_time_min":25,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit & SC/ST","city":"Budgam","tuition_fees":22000,"rating":4.2,"faculty_count":32,"placement_opportunities":"Medium","average_package":4.5,"facilities":["Labs","Library","WiFi"],"extra_curricular":["Science Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 38, "college_name": "Govt. Degree College, Baramulla Vocational", "stream": "Vocational", "subjects":["Textile Designing","ITI Electrician","Hospitality"], "distance_km":15,"travel_time_min":50,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Baramulla","tuition_fees":18000,"rating":4.1,"faculty_count":30,"placement_opportunities":"Medium","average_package":4.0,"facilities":["Labs","Library","WiFi"],"extra_curricular":["Technical Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 39, "college_name": "Govt. Degree College, Jammu Science 2", "stream": "Science", "subjects":["Physics","Chemistry","Mathematics","Computer Science"], "distance_km":7,"travel_time_min":20,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit & SC/ST","city":"Jammu","tuition_fees":22000,"rating":4.3,"faculty_count":32,"placement_opportunities":"Medium","average_package":4.5,"facilities":["Labs","Library","WiFi"],"extra_curricular":["Science Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 40, "college_name": "Govt. Degree College, Anantnag Vocational", "stream": "Vocational", "subjects":["Technical Diploma","Hospitality","IT"], "distance_km":10,"travel_time_min":30,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Anantnag","tuition_fees":19000,"rating":4.2,"faculty_count":30,"placement_opportunities":"Medium","average_package":4.0,"facilities":["Labs","Library","WiFi"],"extra_curricular":["Technical Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},

    # 41-50
    {"college_id": 41, "college_name": "Govt. Degree College, Leh Arts", "stream": "Arts", "subjects":["Psychology","Sociology","Literature"], "distance_km":5,"travel_time_min":15,"hostel":False,"accommodation_type":"PG/Private","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Leh","tuition_fees":15000,"rating":4.0,"faculty_count":25,"placement_opportunities":"Low","average_package":3.0,"facilities":["Library","WiFi"],"extra_curricular":["Drama Club"],"transport_available":False,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 42, "college_name": "Govt. Degree College, Kargil Science 2", "stream": "Science", "subjects":["Physics","Chemistry","Mathematics","Computer Science"], "distance_km":8,"travel_time_min":25,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit & SC/ST","city":"Kargil","tuition_fees":22000,"rating":4.2,"faculty_count":32,"placement_opportunities":"Medium","average_package":4.5,"facilities":["Labs","Library","WiFi"],"extra_curricular":["Science Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 43, "college_name": "Govt. Degree College, Ganderbal Arts 2", "stream": "Arts", "subjects":["History","Literature","Political Science"], "distance_km":7,"travel_time_min":20,"hostel":False,"accommodation_type":"PG/Private","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Ganderbal","tuition_fees":15000,"rating":4.0,"faculty_count":28,"placement_opportunities":"Low","average_package":3.0,"facilities":["Library","WiFi"],"extra_curricular":["Music Club"],"transport_available":False,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 44, "college_name": "Govt. Degree College, Kupwara Science 2", "stream": "Science", "subjects":["Physics","Chemistry","Mathematics","Biology"], "distance_km":12,"travel_time_min":40,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Kupwara","tuition_fees":22000,"rating":4.3,"faculty_count":32,"placement_opportunities":"Medium","average_package":4.5,"facilities":["Labs","Library","WiFi"],"extra_curricular":["Science Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 45, "college_name": "Govt. Degree College, Reasi Arts", "stream": "Arts", "subjects":["Psychology","Sociology","Literature"], "distance_km":18,"travel_time_min":55,"hostel":False,"accommodation_type":"PG/Private","scholarship":False,"scholarship_eligibility":"N/A","city":"Reasi","tuition_fees":15000,"rating":4.0,"faculty_count":25,"placement_opportunities":"Low","average_package":3.0,"facilities":["Library","WiFi"],"extra_curricular":["Drama Club"],"transport_available":False,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 46, "college_name": "Govt. Degree College, Poonch Science", "stream": "Science", "subjects":["Physics","Chemistry","Mathematics","Computer Science"], "distance_km":22,"travel_time_min":70,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit & SC/ST","city":"Poonch","tuition_fees":22000,"rating":4.3,"faculty_count":32,"placement_opportunities":"Medium","average_package":4.5,"facilities":["Labs","Library","WiFi"],"extra_curricular":["Science Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 47, "college_name": "Govt. Degree College, Ramban Arts", "stream": "Arts", "subjects":["History","Literature","Political Science"], "distance_km":16,"travel_time_min":50,"hostel":False,"accommodation_type":"PG/Private","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Ramban","tuition_fees":15000,"rating":4.0,"faculty_count":28,"placement_opportunities":"Low","average_package":3.0,"facilities":["Library","WiFi"],"extra_curricular":["Music Club"],"transport_available":False,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 48, "college_name": "Govt. Degree College, Kishtwar Science", "stream": "Science", "subjects":["Physics","Chemistry","Mathematics","Biology"], "distance_km":20,"travel_time_min":60,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit & SC/ST","city":"Kishtwar","tuition_fees":22000,"rating":4.3,"faculty_count":32,"placement_opportunities":"Medium","average_package":4.5,"facilities":["Labs","Library","WiFi"],"extra_curricular":["Science Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 49, "college_name": "Govt. Degree College, Doda Arts", "stream": "Arts", "subjects":["Psychology","Sociology","Literature"], "distance_km":18,"travel_time_min":60,"hostel":False,"accommodation_type":"PG/Private","scholarship":False,"scholarship_eligibility":"N/A","city":"Doda","tuition_fees":15000,"rating":4.0,"faculty_count":25,"placement_opportunities":"Low","average_package":3.0,"facilities":["Library","WiFi"],"extra_curricular":["Drama Club"],"transport_available":False,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 50, "college_name": "Govt. Degree College, Ramban Science", "stream": "Science", "subjects":["Physics","Chemistry","Mathematics","Computer Science"], "distance_km":16,"travel_time_min":50,"hostel":True,"accommodation_type":"Shared","scholarship":True,"scholarship_eligibility":"Merit-based","city":"Ramban","tuition_fees":22000,"rating":4.3,"faculty_count":32,"placement_opportunities":"Medium","average_package":4.5,"facilities":["Labs","Library","WiFi"],"extra_curricular":["Science Club"],"transport_available":True,"gender_specific":"Co-ed","accreditation":"NAAC B","entry_criteria":"Merit-based"},
    {"college_id": 51, "college_name": "Govt. ITI College, Srinagar", "stream": "Vocational", "subjects":["ITI - Electrician/Mechanic","Technical Diploma","Skilled Trades"], "distance_km":6, "travel_time_min":20, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Srinagar", "tuition_fees":18000, "rating":4.3, "faculty_count":25, "placement_opportunities":"High", "average_package":4.5, "facilities":["Labs","Library","WiFi","Workshop"], "extra_curricular":["Technical Club","Sports Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 52, "college_name": "Govt. ITI College, Jammu", "stream": "Vocational", "subjects":["ITI - Electrician/Mechanic","Skilled Trades","Technical Diploma"], "distance_km":8, "travel_time_min":25, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit & SC/ST", "city":"Jammu", "tuition_fees":19000, "rating":4.2, "faculty_count":28, "placement_opportunities":"Medium", "average_package":4.0, "facilities":["Labs","Library","Workshop"], "extra_curricular":["Technical Club","Coding Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 53, "college_name": "Govt. ITI College, Anantnag", "stream": "Vocational", "subjects":["ITI - Electrician/Mechanic","Technical Diploma","Hospitality"], "distance_km":10, "travel_time_min":30, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Anantnag", "tuition_fees":17500, "rating":4.1, "faculty_count":26, "placement_opportunities":"High", "average_package":4.2, "facilities":["Labs","Library","WiFi","Workshop"], "extra_curricular":["Technical Club","Music Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 54, "college_name": "Govt. ITI College, Baramulla", "stream": "Vocational", "subjects":["ITI - Electrician/Mechanic","Skilled Trades","Technical Diploma"], "distance_km":12, "travel_time_min":40, "hostel":False, "accommodation_type":"PG/Private", "scholarship":True, "scholarship_eligibility":"Merit & SC/ST", "city":"Baramulla", "tuition_fees":18000, "rating":4.0, "faculty_count":24, "placement_opportunities":"Medium", "average_package":3.8, "facilities":["Labs","Library","Workshop"], "extra_curricular":["Technical Club","Art Club"], "transport_available":False, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"},
    {"college_id": 55, "college_name": "Govt. ITI College, Kulgam", "stream": "Vocational", "subjects":["ITI - Electrician/Mechanic","Skilled Trades","Technical Diploma"], "distance_km":9, "travel_time_min":30, "hostel":True, "accommodation_type":"Shared", "scholarship":True, "scholarship_eligibility":"Merit-based", "city":"Kulgam", "tuition_fees":18000, "rating":4.1, "faculty_count":25, "placement_opportunities":"High", "average_package":4.3, "facilities":["Labs","Library","WiFi","Workshop"], "extra_curricular":["Technical Club","Sports Club"], "transport_available":True, "gender_specific":"Co-ed", "accreditation":"NAAC B", "entry_criteria":"Merit-based"}
]

# Quiz Mapping
QUIZ_TO_SUBJECT_CAREER = {
    "Science": {
        "math_interest": ("Mathematics", "Engineering/Data Science"),
        "chemistry_interest": ("Chemistry", "Chemistry/Pharma"),
        "biology_interest": ("Biology", "Medicine/Biotech"),
        "cs_interest": ("Computer Science", "Computer Science/IT"),
        "physics_interest": ("Physics", "Physicist/Researcher")
    },
    "Arts": {
        "writing_interest": ("Literature", "Literature/Journalism"),
        "history_interest": ("History", "Historian/Teacher"),
        "politics_interest": ("Political Science", "UPSC/Law/Political Science"),
        "sociology_interest": ("Sociology", "NGO/Social Work"),
        "arts_interest": ("Fine Arts", "Fine Arts/Design")
    },
    "Commerce": {
        "accounting_interest": ("Accounting", "Chartered Accountant/Finance"),
        "economics_interest": ("Economics", "Economist/Banking"),
        "finance_interest": ("Finance", "MBA/Entrepreneur"),
        "business_interest": ("Business Studies", "Business Manager"),
        "marketing_interest": ("Marketing", "Marketing/Sales")
    },
    "Vocational": {
        "technical_skills_interest": ("ITI - Electrician/Mechanic", "ITI Electrician/Mechanic"),
        "hospitality_interest": ("Hospitality", "Chef/Hotel Management"),
        "design_interest": ("Fashion Design", "Designer/Fashion"),
        "practical_learning_interest": ("Technical Diploma", "Technical Diploma"),
        "tools_interest": ("Skilled Trades", "Skilled Trades")
    }
}

QUIZ_QUESTIONS = {
    "scientific_interest_score": [
        "I enjoy learning about how the universe and natural world work.",
        "I like creating things and understanding the technology behind them.",
        "I am curious about analyzing data and performing experiments."
    ],
    "creativity_score": [
        "I enjoy drawing, painting, writing, or other artistic activities.",
        "I often think of unique and non-traditional solutions to problems.",
        "I am interested in history, culture, and social issues."
    ],
    "business_interest_score": [
        "I am interested in understanding how businesses and money work.",
        "I enjoy convincing others or selling ideas/products.",
        "I like planning, organizing, and managing events or projects."
    ]
}
